In [20]:
# Data Exploration and Preprocessing

import pandas as pd
data = pd.read_csv('/content/adult_with_headers.csv')
data

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [22]:
data.describe(include='all')

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
count,32561.000000,32561,3.256100e+04,32561,32561.000000,32561,32561,32561,32561,32561,32561.000000,32561.000000,32561.000000,32561,32561
unique,NaN,9,NaN,16,NaN,7,15,6,5,2,NaN,NaN,NaN,42,2
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,22696,NaN,10501,NaN,14976,4140,13193,27816,21790,NaN,NaN,NaN,29170,24720
mean,38.581647,NaN,1.897784e+05,NaN,10.080679,NaN,NaN,NaN,NaN,NaN,1077.648844,87.303830,40.437456,NaN,NaN
std,13.640433,NaN,1.055500e+05,NaN,2.572720,NaN,NaN,NaN,NaN,NaN,7385.292085,402.960219,12.347429,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.178270e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.783560e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.370510e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.484705e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [23]:
#missing_values
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [24]:
for column in data.columns:
  if data[column].isnull().sum()>0:
    if data[column].dtype=='object':
      data[column].fillna(data[column].mode()[0],inplace=True)
    else:
      data[column].fillna(data[column].mean(),inplace=True)

In [25]:
#	Apply scaling techniques to numerical features:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler_standard = StandardScaler()
data_standard_scaled = data.copy()
data_standard_scaled[data_standard_scaled.select_dtypes(include=['int64', 'float64']).columns] = scaler_standard.fit_transform(data_standard_scaled.select_dtypes(include=['int64', 'float64']))
data_standard_scaled

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.030671,State-gov,-1.063611,Bachelors,1.134739,Never-married,Adm-clerical,Not-in-family,White,Male,0.148453,-0.21666,-0.035429,United-States,<=50K
1,0.837109,Self-emp-not-inc,-1.008707,Bachelors,1.134739,Married-civ-spouse,Exec-managerial,Husband,White,Male,-0.145920,-0.21666,-2.222153,United-States,<=50K
2,-0.042642,Private,0.245079,HS-grad,-0.420060,Divorced,Handlers-cleaners,Not-in-family,White,Male,-0.145920,-0.21666,-0.035429,United-States,<=50K
3,1.057047,Private,0.425801,11th,-1.197459,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,-0.145920,-0.21666,-0.035429,United-States,<=50K
4,-0.775768,Private,1.408176,Bachelors,1.134739,Married-civ-spouse,Prof-specialty,Wife,Black,Female,-0.145920,-0.21666,-0.035429,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,-0.849080,Private,0.639741,Assoc-acdm,0.746039,Married-civ-spouse,Tech-support,Wife,White,Female,-0.145920,-0.21666,-0.197409,United-States,<=50K
32557,0.103983,Private,-0.335433,HS-grad,-0.420060,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,-0.145920,-0.21666,-0.035429,United-States,>50K
32558,1.423610,Private,-0.358777,HS-grad,-0.420060,Widowed,Adm-clerical,Unmarried,White,Female,-0.145920,-0.21666,-0.035429,United-States,<=50K
32559,-1.215643,Private,0.110960,HS-grad,-0.420060,Never-married,Adm-clerical,Own-child,White,Male,-0.145920,-0.21666,-1.655225,United-States,<=50K
32560,0.983734,Self-emp-inc,0.929893,HS-grad,-0.420060,Married-civ-spouse,Exec-managerial,Wife,White,Female,1.888424,-0.21666,-0.035429,United-States,>50K

In [26]:
scaler_minmax=MinMaxScaler()
data_minmax_scaled=data.copy()
data_minmax_scaled[data_minmax_scaled.select_dtypes(include=['int64','float64']).columns]=scaler_minmax.fit_transform(data_minmax_scaled.select_dtypes(include=['int64','float64']))
data_minmax_scaled

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,Male,0.021740,0.0,0.397959,United-States,<=50K
1,0.452055,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.000000,0.0,0.122449,United-States,<=50K
2,0.287671,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.000000,0.0,0.397959,United-States,<=50K
3,0.493151,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.000000,0.0,0.397959,United-States,<=50K
4,0.150685,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.000000,0.0,0.397959,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,0.136986,Private,0.166404,Assoc-acdm,0.733333,Married-civ-spouse,Tech-support,Wife,White,Female,0.000000,0.0,0.377551,United-States,<=50K
32557,0.315068,Private,0.096500,HS-grad,0.533333,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.000000,0.0,0.397959,United-States,>50K
32558,0.561644,Private,0.094827,HS-grad,0.533333,Widowed,Adm-clerical,Unmarried,White,Female,0.000000,0.0,0.397959,United-States,<=50K
32559,0.068493,Private,0.128499,HS-grad,0.533333,Never-married,Adm-clerical,Own-child,White,Male,0.000000,0.0,0.193878,United-States,<=50K
32560,0.479452,Self-emp-inc,0.187203,HS-grad,0.533333,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.150242,0.0,0.397959,United-States,>50K

In [27]:
# 2.Encoding Techniques
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
categorical_columns = [col for col in data.select_dtypes(include=['object']).columns if data[col].nunique() < 5]
data_one_hot_encoded = pd.get_dummies(data, columns=categorical_columns)
data_one_hot_encoded

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,2174,0,40,United-States,0,1,1,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,13,United-States,0,1,1,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,40,United-States,0,1,1,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,40,United-States,0,1,1,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,40,Cuba,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,0,0,38,United-States,1,0,1,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,0,0,40,United-States,0,1,0,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,0,0,40,United-States,1,0,1,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,0,0,20,United-States,0,1,1,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,15024,0,40,United-States,1,0,0,1

In [28]:
label_encoder = LabelEncoder()
for col in data.select_dtypes(include=['object']).columns:
    if col not in categorical_columns:
        data[col] = label_encoder.fit_transform(data[col])
label_encoder

LabelEncoder()

In [29]:
# Example of creating new features
data['hours_per_week_squared'] = data['hours_per_week'] ** 2
data['age_income_ratio'] = data['age'] / (data['capital_gain'] + 1)
data['hours_per_week_squared'],data['age_income_ratio']

(0        1600
 1         169
 2        1600
 3        1600
 4        1600
          ...
 32556    1444
 32557    1600
 32558    1600
 32559     400
 32560    1600
 Name: hours_per_week_squared, Length: 32561, dtype: int64,
 0         0.017931
 1        50.000000
 2        38.000000
 3        53.000000
 4        28.000000
            ...
 32556    27.000000
 32557    40.000000
 32558    58.000000
 32559    22.000000
 32560     0.003461
 Name: age_income_ratio, Length: 32561, dtype: float64)

In [30]:
#Apply a transformation
import numpy as np
data['capital_gain'] = np.log1p(data['capital_gain'])
data['capital_gain']

0        7.684784
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...
32556    0.000000
32557    0.000000
32558    0.000000
32559    0.000000
32560    9.617471
Name: capital_gain, Length: 32561, dtype: float64

In [31]:
# Feature Selection

from sklearn.ensemble import IsolationForest
iso_forest = IsolationForest(contamination=0.1)
outliers = iso_forest.fit_predict(data.select_dtypes(include=['int64', 'float64']))
data_no_outliers = data[outliers == 1]
iso_forest

IsolationForest(contamination=0.1)

In [32]:
outliers

array([ 1,  1,  1, ...,  1,  1, -1])

In [33]:
data_no_outliers

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,hours_per_week_squared,age_income_ratio
0,39,7,77516,9,13,4,1,1,4,Male,7.684784,0,40,39,<=50K,1600,0.017931
1,50,6,83311,9,13,2,4,0,4,Male,0.000000,0,13,39,<=50K,169,50.000000
2,38,4,215646,11,9,0,6,1,4,Male,0.000000,0,40,39,<=50K,1600,38.000000
3,53,4,234721,1,7,2,6,0,2,Male,0.000000,0,40,39,<=50K,1600,53.000000
5,37,4,284582,12,14,2,4,5,4,Female,0.000000,0,40,39,<=50K,1600,37.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,22,4,310152,15,10,4,11,1,4,Male,0.000000,0,40,39,<=50K,1600,22.000000
32556,27,4,257302,7,12,2,13,5,4,Female,0.000000,0,38,39,<=50K,1444,27.000000
32557,40,4,154374,11,9,2,7,0,4,Male,0.000000,0,40,39,>50K,1600,40.000000
32558,58,4,151910,11,9,6,1,4,4,Female,0.000000,0,40,39,<=50K,1600,58.000000
32559,22,4,201490,11,9,4,1,3,4,Male,0.000000,0,20,39,<=50K,400,22.000000

In [34]:
!pip install ppscore

Requirement already satisfied: ppscore in /usr/local/lib/python3.10/dist-packages (1.3.0)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ppscore) (1.5.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.10/dist-packages (from ppscore) (1.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.16.0)

In [35]:
# Apply PPS (Predictive Power Score):
import ppscore as pps
pps_matrix = pps.matrix(data)
pps_matrix

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,age,age,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,age,workclass,0.000000,regression,True,mean absolute error,0.742600,0.875681,DecisionTreeRegressor()
2,age,fnlwgt,0.000000,regression,True,mean absolute error,75872.186200,77535.141544,DecisionTreeRegressor()
3,age,education,0.000000,regression,True,mean absolute error,2.759000,2.806164,DecisionTreeRegressor()
4,age,education_num,0.000000,regression,True,mean absolute error,1.853000,1.898306,DecisionTreeRegressor()
...,...,...,...,...,...,...,...,...,...
284,age_income_ratio,hours_per_week,0.000000,regression,True,mean absolute error,7.656400,8.271373,DecisionTreeRegressor()
285,age_income_ratio,native_country,0.000000,regression,True,mean absolute error,2.374800,4.245985,DecisionTreeRegressor()
286,age_income_ratio,income,0.238418,classification,True,weighted F1,0.653115,0.735819,DecisionTreeClassifier()
287,age_income_ratio,hours_per_week_squared,0.000000,regression,True,mean absolute error,626.045600,715.025213,DecisionTreeRegressor()
288,age_income_ratio,age_income_ratio,1.000000,predict_itself,True,None,0.000000,1.000000,None

In [36]:
correlation_matrix = data.corr()
correlation_matrix

<ipython-input-36-6617581d08be>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = data.corr()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,hours_per_week_squared,age_income_ratio
age,1.000000,0.003787,-0.076646,-0.010508,0.036527,-0.266288,-0.020947,-0.263698,0.028718,0.124183,0.057775,0.068756,-0.001151,0.072882,0.664370
workclass,0.003787,1.000000,-0.016656,0.023513,0.052085,-0.064731,0.254892,-0.090461,0.049742,0.022672,0.012216,0.138962,-0.007690,0.129954,-0.006390
fnlwgt,-0.076646,-0.016656,1.000000,-0.028145,-0.043195,0.028153,0.001597,0.008931,-0.021291,-0.004414,-0.010252,-0.018768,-0.051966,-0.027353,-0.054557
education,-0.010508,0.023513,-0.028145,1.000000,0.359153,-0.038407,-0.021260,-0.010876,0.014131,0.024955,0.016746,0.055510,0.064288,0.045272,-0.023016
education_num,0.036527,0.052085,-0.043195,0.359153,1.000000,-0.069304,0.109697,-0.094153,0.031838,0.129135,0.079923,0.148123,0.050840,0.136576,-0.055283
marital_status,-0.266288,-0.064731,0.028153,-0.038407,-0.069304,1.000000,-0.009654,0.185451,-0.068013,-0.066595,-0.034187,-0.190519,-0.023819,-0.158243,-0.165450
occupation,-0.020947,0.254892,0.001597,-0.021260,0.109697,-0.009654,1.000000,-0.075607,0.006763,0.019852,0.017987,0.080383,-0.012543,0.080672,-0.024560
relationship,-0.263698,-0.090461,0.008931,-0.010876,-0.094153,0.185451,-0.075607,1.000000,-0.116055,-0.083402,-0.061062,-0.248974,-0.005507,-0.225190,-0.146738
race,0.028718,0.049742,-0.021291,0.014131,0.031838,-0.068013,0.006763,-0.116055,1.000000,0.024089,0.018899,0.041910,0.137852,0.047632,0.002313
capital_gain,0.124183,0.022672,-0.004414,0.024955,0.129135,-0.066595,0.019852,-0.083402,0.024089,1.000000,-0.064840,0.083821,0.005701,0.078828,-0.624963
capital_loss,0.057775,0.012216,-0.010252,0.016746,0.079923,-0.034187,0.017987,-0.061062,0.018899,-0.064840,1.000000,0.054256,0.000419,0.051843,0.094651
hours_per_week,0.068756,0.138962,-0.018768,0.055510,0.148123,-0.190519,0.080383,-0.248974,0.041910,0.083821,0.054256,1.000000,-0.002671,0.950920,0.007477
native_country,-0.001151,-0.007690,-0.051966,0.064288,0.050840,-0.023819,-0.012543,-0.005507,0.137852,0.005701,0.000419,-0.002671,1.000000,0.001263,-0.004357
hours_per_week_squared,0.072882,0.129954,-0.027353,0.045272,0.136576,-0.158243,0.080672,-0.225190,0.047632,0.078828,0.051843,0.950920,0.001263,1.000000,0.011628
age_income_ratio,0.664370,-0.006390,-0.054557,-0.023016,-0.055283,-0.165450,-0.024560,-0.146738,0.002313,-0.624963,0.094651,0.007477,-0.004357,0.011628,1.000000